---
# Non-sensitive variables
deployment_environment: "dev"

# Oracle Cloud variables
oci_tenancy_ocid: "{{ vault_oci_tenancy_ocid }}"
oci_user_ocid: "{{ vault_oci_user_ocid }}"
oci_fingerprint: "{{ vault_oci_fingerprint }}"
oci_private_key_path: "{{ vault_oci_private_key_path }}"
oci_region: "eu-stockholm-1"
oci_compartment_id: "{{ vault_oci_tenancy_ocid }}"  # Using tenancy as compartment

# VM configuration
availability_domain: "GiQi:EU-STOCKHOLM-1-AD-1"
windows_image_id: "ocid1.image.oc1.eu-stockholm-1.aaaaaaaavvubpflzqzb3i3fgw2rj72jsomhxubi4g7mjgp5jdofokqrbkn5q"
ssh_public_key: "{{ vault_ssh_public_key }}"

# Network configuration
vcn_name: "sqlserver-vcn"
vcn_cidr: "10.0.0.0/16"

# SQL Server configuration
sql_server_data_dir: "C:\\SQLData"
sql_server_log_dir: "C:\\SQLLogs"
sql_server_backup_dir: "C:\\SQLBackup"
