---
# Non-sensitive variables
deployment_environment: "dev"

# Azure variables
azure_subscription_id: "{{ vault_azure_subscription_id }}"
azure_tenant_id: "{{ vault_azure_tenant_id }}"
azure_client_id: "{{ vault_azure_client_id }}"
azure_client_secret: "{{ vault_azure_client_secret }}"
azure_location: "westeurope"
azure_resource_group_name: "sql-server-rg"

# VM configuration
azure_vm_size: "Standard_B1s"
azure_admin_username: "janne"
azure_admin_password: "{{ vault_windows_admin_password }}"

# Common configuration
ssh_public_key: "{{ vault_ssh_public_key }}"

# Network configuration
azure_vnet_name: "sql-server-vnet"
azure_vnet_cidr: "10.0.0.0/16"

# SQL Server configuration
sql_server_data_dir: "C:\\SQLData"
sql_server_log_dir: "C:\\SQLLogs"
sql_server_backup_dir: "C:\\SQLBackup"
