---
- name: Ensure PowerShell execution policy is unrestricted
  win_shell: Set-ExecutionPolicy Unrestricted -Force
  
- name: Enable Remote Desktop
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    data: 0
    type: dword

- name: Enable Remote Desktop firewall rule
  win_shell: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

- name: Create required directories
  win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - "S:\\SQLData"
    - "S:\\SQLLogs"
    - "S:\\SQLBackup" 