---
- name: Ensure PowerShell execution policy is unrestricted
  ansible.windows.win_shell: Set-ExecutionPolicy Unrestricted -Force

- name: Enable Remote Desktop
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    data: 0
    type: dword

- name: Enable Remote Desktop firewall rule
  ansible.windows.win_shell: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

- name: Create required directories
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ sql_server_data_dir }}"
    - "{{ sql_server_log_dir }}"
    - "{{ sql_server_backup_dir }}"
