---
all:
  children:
    windows:
      hosts:
        sqlserver:
          ansible_host: 13.93.83.98
      vars:
        ansible_user: janne
        ansible_password: gu1nneSS11!!
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_transport: basic
        ansible_port: 5985
