---
- name: Test OCI Connection
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Test OCI CLI Configuration
      ansible.builtin.command: oci iam compartment list
      ignore_errors: true
      changed_when: false
      register: oci_cli_test

    - name: Display OCI CLI test results
      ansible.builtin.debug:
        msg: "OCI CLI {{ 'is configured correctly' if oci_cli_test.rc == 0 else 'failed - make sure OCI CLI is installed and configured' }}"

    - name: Test OCI API Connection
      ansible.builtin.command: >
        oci compute shape list --compartment-id ocid1.tenancy.oc1..aaaaaaaawcczb6nidnd6rfoqmbvqg6dihslqsrrgnw6kysz6yix4lcvig2va
      ignore_errors: true
      changed_when: false
      register: oci_api_test
      environment:
        SUPPRESS_LABEL_WARNING: "True"

    - name: Display available shapes
      ansible.builtin.debug:
        msg: "Shape listing {{ 'succeeded' if oci_api_test.rc == 0 else 'failed' }}"
      when: oci_api_test.rc is defined

    - name: Test Windows Server 2019 image access
      ansible.builtin.command: >
        oci compute image get
        --image-id ocid1.image.oc1.eu-stockholm-1.aaaaaaaavvubpflzqzb3i3fgw2rj72jsomhxubi4g7mjgp5jdofokqrbkn5q
      register: image_result
      ignore_errors: true
      changed_when: false
      environment:
        SUPPRESS_LABEL_WARNING: "True"

    - name: Display image test results
      ansible.builtin.debug:
        msg: "Windows Server image test {{ 'succeeded' if image_result.rc == 0 else 'failed' }}"
      when: image_result.rc is defined

    - name: Report test status
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - "==============================================="
        - "OCI CLI configuration: {{ 'OK' if oci_cli_test.rc == 0 else 'FAILED' }}"
        - "Shape listing: {{ 'OK' if oci_api_test.rc == 0 else 'FAILED' }}"
        - "Windows image: {{ 'OK' if image_result.rc == 0 else 'FAILED' }}"
        - "==============================================="
      when: oci_cli_test.rc is defined and oci_api_test.rc is defined and image_result.rc is defined
