---
- name: Debug Variables
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Display loaded variables
      ansible.builtin.debug:
        msg: 
          - "oci_tenancy_ocid (exists: {{ oci_tenancy_ocid is defined }})"
          - "vault_oci_tenancy_ocid (exists: {{ vault_oci_tenancy_ocid is defined }})"

    - name: Show inventory sources
      ansible.builtin.debug:
        var: ansible_inventory_sources
        
    - name: Show group_vars directory contents
      ansible.builtin.command: ls -la "{{ playbook_dir }}/group_vars/all"
      register: ls_output
      changed_when: false
      
    - name: Display group_vars contents
      ansible.builtin.debug:
        var: ls_output.stdout_lines
