---
- name: Diagnose Variable Issues
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Display all current variables
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
        verbosity: 1

    - name: Check if vars.yml is loaded
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/group_vars/all/vars.yml"
      register: vars_file

    - name: Display vars.yml status
      ansible.builtin.debug:
        msg: "vars.yml {{ 'exists' if vars_file.stat.exists else 'MISSING' }}"

    - name: Check if vault.yml is loaded
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/group_vars/all/vault.yml"
      register: vault_file

    - name: Display vault.yml status
      ansible.builtin.debug:
        msg: "vault.yml {{ 'exists' if vault_file.stat.exists else 'MISSING' }}"

    - name: List critical variables
      ansible.builtin.debug:
        msg:
          - "azure_subscription_id: {{ azure_subscription_id | default('UNDEFINED') }}"
          - "azure_tenant_id: {{ azure_tenant_id | default('UNDEFINED') }}"
          - "azure_client_id: {{ azure_client_id | default('UNDEFINED') }}"
          - "azure_client_secret: {{ azure_client_secret | default('UNDEFINED') }}"
          - "azure_location: {{ azure_location | default('UNDEFINED') }}"
          - "azure_resource_group_name: {{ azure_resource_group_name | default('UNDEFINED') }}"
          - "azure_vm_size: {{ azure_vm_size | default('UNDEFINED') }}"
          - "azure_admin_username: {{ azure_admin_username | default('UNDEFINED') }}"
          - "azure_admin_password: {{ azure_admin_password | default('UNDEFINED') }}"
          - "ssh_public_key: {{ ssh_public_key | default('UNDEFINED') }}"

    - name: Check vault variables
      ansible.builtin.debug:
        msg:
          - "vault_azure_subscription_id: {{ vault_azure_subscription_id | default('UNDEFINED') }}"
          - "vault_azure_tenant_id: {{ vault_azure_tenant_id | default('UNDEFINED') }}"
          - "vault_azure_client_id: {{ vault_azure_client_id | default('UNDEFINED') }}"
          - "vault_azure_client_secret: {{ vault_azure_client_secret | default('UNDEFINED') }}"
          - "vault_windows_admin_password: {{ vault_windows_admin_password | default('UNDEFINED') }}"
          - "vault_ssh_public_key: {{ vault_ssh_public_key | default('UNDEFINED') }}"
