---
- name: Diagnose Variable Issues
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Display all current variables
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
        verbosity: 1

    - name: Check if vars.yml is loaded
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/group_vars/all/vars.yml"
      register: vars_file

    - name: Display vars.yml status
      ansible.builtin.debug:
        msg: "vars.yml {{ 'exists' if vars_file.stat.exists else 'MISSING' }}"

    - name: Check if vault.yml is loaded
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/group_vars/all/vault.yml"
      register: vault_file

    - name: Display vault.yml status
      ansible.builtin.debug:
        msg: "vault.yml {{ 'exists' if vault_file.stat.exists else 'MISSING' }}"

    - name: List critical variables
      ansible.builtin.debug:
        msg:
          - "oci_tenancy_ocid: {{ oci_tenancy_ocid | default('UNDEFINED') }}"
          - "oci_user_ocid: {{ oci_user_ocid | default('UNDEFINED') }}"
          - "oci_fingerprint: {{ oci_fingerprint | default('UNDEFINED') }}"
          - "oci_private_key_path: {{ oci_private_key_path | default('UNDEFINED') }}"
          - "oci_region: {{ oci_region | default('UNDEFINED') }}"
          - "oci_compartment_id: {{ oci_compartment_id | default('UNDEFINED') }}"
          - "availability_domain: {{ availability_domain | default('UNDEFINED') }}"
          - "windows_image_id: {{ windows_image_id | default('UNDEFINED') }}"
          - "ssh_public_key: {{ ssh_public_key | default('UNDEFINED') }}"

    - name: Check vault variables
      ansible.builtin.debug:
        msg:
          - "vault_oci_tenancy_ocid: {{ vault_oci_tenancy_ocid | default('UNDEFINED') }}"
          - "vault_oci_user_ocid: {{ vault_oci_user_ocid | default('UNDEFINED') }}"
          - "vault_oci_fingerprint: {{ vault_oci_fingerprint | default('UNDEFINED') }}"
          - "vault_oci_private_key_path: {{ vault_oci_private_key_path | default('UNDEFINED') }}"
          - "vault_ssh_public_key: {{ vault_ssh_public_key | default('UNDEFINED') }}"
