---
# Import infrastructure deployment playbook
- name: Deploy infrastructure to Azure
  ansible.builtin.import_playbook: "{{ playbook_dir }}/playbooks/deploy_infrastructure.yml"

# Import SQL Server configuration playbook
- name: Configure SQL Server on Windows VM
  ansible.builtin.import_playbook: "{{ playbook_dir }}/playbooks/configure_sql_server.yml"
