---
# Import infrastructure deployment playbook
- name: Deploy infrastructure to Azure
  import_playbook: "{{ playbook_dir }}/playbooks/deploy_infrastructure.yml"

# Import SQL Server configuration playbook
- name: Configure SQL Server on Windows VM
  import_playbook: "{{ playbook_dir }}/playbooks/setup_sql_server.yml"
